# This is a placeholder hardware configuration for the work PC
# You'll need to replace this with the actual hardware configuration
# generated by nixos-generate-config on the work machine

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Basic hardware configuration
  # Update this when you generate the actual configuration on the work machine
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Placeholder filesystem configuration - replace with actual work PC configuration
  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  # Placeholder swap configuration
  swapDevices = [ ];

  # Host platform configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
